baseURL = "https://huyaduo1.github.io/blog/"
title = "浅忆 / Personal Brand"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
timeZone = "Asia/Shanghai"
staticDir = ["static", "res"]
canonifyURLs = false
enableRobotsTXT = true

[permalinks]
  posts = "/posts/:slugorfilename/"

[params]
  katex = true
  mermaid = true
  author = "浅忆"
  description = "淡雅极简的个人简历与博客"
  footer = "© 2026 浅忆"

[markup]
  [markup.highlight]
    style = "gruvbox-light"
    noClasses = true
    lineNos = false
    tabWidth = 2
    codeFences = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[taxonomies]
  tag = "tags"
